apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-2
  namespace: ns-a
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-2
    spec:
      containers:
      - name: test
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: secr
          mountPath: /secr
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate insteada
              command: ["/usr/sbin/nginx","-s","quit"]



      volumes:
      - name: secr
        emptyDir: {}
