apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 0
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
      - name: test
        image: nginx:1.11.1
