apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-2
  namespace: ns-a
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: nginx-2
    spec:
      containers:
      - name: test
        image: nginx:1.11
        volumeMounts:
        - name: secr
          mountPath: /secr
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/usr/sbin/nginx","-s","quit"]



      volumes:
      - name: secr
        secret:
          secretName: sec-ngx-2
