apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-2
  namespace: ns-a
spec:
  replicas: 0
  template:
    metadata:
      labels:
        run: nginx-2
    spec:
      containers:
      - name: test
        image: nginx:latest
        volumeMounts:
        - name: secr
          mountPath: /secr
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate insteada
              command: ["/usr/sbin/nginx","-s","quit"]



      volumes:
      - name: secr
        emptyDir: {}
