apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: provisioner
    spec:
      containers:
      - name: git-sync
        image: lukaszbielinski/git-sync:0.5
        resources:
          limits:
            cpu: 500m
            memory: "700Mi"
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: markdown
          mountPath: /git
        - name: secr
          mountPath: /root/.ssh/klucze
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/lukasz-bielinski/test
        - name: GIT_SYNC_WAIT
          value: "5"
        - name: GIT_SYNC_DEST
          value: /git

      - name: kubectl-image
        image: lukaszbielinski/kubectl-image:0.4
        resources:
          limits:
            cpu: 500m
            memory: "700Mi"
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        volumeMounts:
        - name: markdown
          mountPath: /src

      volumes:
      - name: markdown
        emptyDir: {}
      - name: secr
        secret:
          secretName: testsec
