apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisioner-secrets
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: depsec
    spec:
      containers:
      - name: git-sync
        image: lukaszbielinski/git-sync:0.6
        imagePullPolicy: Always
        volumeMounts:
        - name: markdown
          mountPath: /git
        - name: klucze
          mountPath: /root/.ssh/klucze
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/lukasz-bielinski/test-secrets
        - name: GIT_SYNC_WAIT
          value: "10"
        - name: GIT_SYNC_DEST
          value: /git



      - name: secprov
        image: lukaszbielinski/kubectl-image:0.20-secrets
        imagePullPolicy: Always
        volumeMounts:
        - name: markdown
          mountPath: /srcsecrets

      volumes:
      - name: markdown
        emptyDir: {}
      - name: klucze
        secret:
          secretName: klucze
