kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:3.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 30


---



kind: Service
apiVersion: v1
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  externalIPs:
  - 192.168.1.181
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
