apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system

spec:
  template:
    metadata:
      labels:
        name: kube-proxy

    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: newrelic
      hostNetwork: true
      containers:
          - name: kube-proxy
            image: quay.io/coreos/hyperkube:v1.4.1_coreos.0
            command:
            - /hyperkube
            - proxy
            - --master=https://192.168.1.140
            - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
            - --proxy-mode=iptables
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /etc/ssl/certs
                name: "ssl-certs"
              - mountPath: /etc/kubernetes/worker-kubeconfig.yaml
                name: "kubeconfig"
                readOnly: true
              - mountPath: /etc/kubernetes/ssl
                name: "etc-kube-ssl"
                readOnly: true

      terminationGracePeriodSeconds: 1
      volumes:
        - name: "ssl-certs"
          hostPath:
            path: "/usr/share/ca-certificates"
        - name: "kubeconfig"
          hostPath:
            path: "/etc/kubernetes/worker-kubeconfig.yaml"
        - name: "etc-kube-ssl"
          hostPath:
            path: "/etc/kubernetes/ssl"
