apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: vip
  name: external-ip-vip
  labels:
    app-name: keepalived-vip

spec:
  template:
    metadata:
      labels:
        name: keepalived-vip

    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      nodeSelector:
        zone: fe-prod

      containers:
        - name: keepalived-vip
          image: oberthur/docker-keepalived:20160917
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 32Mi
          #   limits:
          #     cpu: 1
          #     memory: 48Mi
          env:
            - name: VIP
              value: "192.168.1.22"
            - name: MASK
              value: "24"
            - name: VROUTERID
              value: "2"
            - name: STATE
              value: "BACKUP"
            - name: INTERFACE
              value: "eth0"
            - name: PRIORITY
              value: "100"
            - name: ADVERT
              value: "1"
            - name: AUTHPASS
              value: "c4b1a603092ec2e7e9fb995f57ebd659"
