kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-deployment
  namespace: kafka-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image:  cloudtrackinc/kubernetes-kafka:latest
        ports:
        - containerPort: 9092
        env:
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181
          - name: KAFKA_CREATE_TOPICS
            value: demo-topic:3:2


##usr/bin/kafka-consumer-offset-checker --group flume --topic testf --zookeeper zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181
##kafka-console-consumer.sh --zookeeper zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181 --from-beginning --topic testf
##kafka-topics.sh --create --replication-factor 2 --partitions 1 --topic test3 --zookeeper zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181
##kafka-topics.sh --list --zookeeper zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181
##kafka-topics.sh  --zookeeper zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181 --delete --topic your_topic_name
##kafka-topics.sh --describe --zookeeper zoo1.kafka-cluster:2181,zoo2.kafka-cluster:2181,zoo3.kafka-cluster:2181  --topic test3
