apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisioner-deployments
  namespace: provisioners
spec:
  replicas: 1
  strategy:
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  template:
    metadata:
      labels:
        run: provdeployments
    spec:
      containers:
      - name: git-sync
        image: lukaszbielinski/git-sync:mode9
        imagePullPolicy: Always
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "150Mi"
            cpu: "50m"
        volumeMounts:
        - name: markdown
          mountPath: /git
        - name: klucze
          mountPath: /root/.ssh
        env:
        - name: GIT_SYNC_REPO
          value: git@github.com:lukasz-bielinski/test.git
        - name: GIT_SYNC_WAIT
          value: "5"
        - name: GIT_SYNC_DEST
          value: /git
        - name: GIT_PULL_TYPE
          value: HSA


      - name: prov
        image: lukaszbielinski/kubectl-image:0.28-kubectl-lock
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "100m"
        volumeMounts:
        - name: markdown
          mountPath: /src
        env:
        - name: DEPLOYMENT_DIR
          value:
        - name: PROV_TYPE
          value: generic

      terminationGracePeriodSeconds: 2


      volumes:
      - name: markdown
        emptyDir: {}
      - name: klucze
        secret:
          secretName: klucze
###
