apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: loggingru
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 2
  strategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-client
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:2.4.0
        resources:
                requests:
                  cpu: 10m
                  memory: 1000Mi
                limits:
                  cpu: 1000m
                  memory: 1000Mi

        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: ES_HEAP_SIZE
          value: "500m"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: "NUMBER_OF_REPLICAS"
          value: "2"
        - name: "NUMBER_OF_SHARDS"
          value: "2"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.loggingru"

        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP

        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","/hooks/poststart.sh"]
          preStop:
            exec:
              command: ["/bin/bash","/hooks/prestop.sh"]

        volumeMounts:
        - mountPath: /data
          name: storage
        - name: hooks
          mountPath: /hooks

        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 30
          timeoutSeconds: 5

        readinessProbe:
          tcpSocket:
              port: 9200
          initialDelaySeconds: 30
          timeoutSeconds: 5

      terminationGracePeriodSeconds: 1800
      volumes:
      - name: storage
        emptyDir: {}
      - name: hooks
        secret:
          secretName: hooks
      nodeSelector:
          zone: "be-prod"
