apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logging
  namespace: loggingru
  labels:
    tier: monitoring
    app: fluentd-agent
spec:
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: newrelic
      containers:
          - name: fluentd
            image: lukaszbielinski/docker-fluentd-kubernetes:0.4
            volumeMounts:
              - name: varlog
                mountPath: /var/log
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
            env:
              - name: ELASTICSEARCH_HOST
                value: elasticsearch.loggingru
              - name: ELASTICSEARCH_PORT
                value: "9200"


      terminationGracePeriodSeconds: 30
      volumes:
       - name: fluentd
         secret:
           secretName: fluentd
       - name: varlog
         hostPath:
           path: /var/log
       - name: varlibdockercontainers
         hostPath:
           path: /var/lib/docker/containers
