apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: rollerd
  name: rollerd
  namespace: default
spec:
  replicas: 0
  selector:
    app: rollerd
  template:
    metadata:
      labels:
        app: rollerd
    spec:
      containers:
      - env:
        - name: COREROLLER_DB_URL
          value: postgres://postgres@postgresql:5432/coreroller?sslmode=disable
        image: coreroller/rollerd
        imagePullPolicy: Always
        name: rollerd
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
